add PELE Network
zilpay/snapshot-spaces pull request #34
Opened 2021-09-15 22:46 UTC by jordanurbs

Add space for PELE Network

Website: https://www.pele.network  
Telegram: https://t.me/PELENetwork
Twitter: https://twitter.com/PELENetwork

2021-10-04 05:29 UTC, bb111189 requested changes

2021-10-04 05:29 UTC, bb111189 commented on spaces/pele/index.json
> +  "token": "zil18f5rlhqz9vndw4w8p60d0n7vg3n9sqvta7n6t2",
This token belong to PORT token

2021-10-18 02:40 UTC, jordanurbs reviewed
fix PELE token address

2021-10-18 02:41 UTC, jordanurbs commented on spaces/pele/index.json
> +  "token": "zil18f5rlhqz9vndw4w8p60d0n7vg3n9sqvta7n6t2",
Fixed.

2021-11-07 03:44 UTC, jordanurbs commented
Bump. Anything?

2021-11-07 16:47 UTC, bb111189 approved these changes

2021-11-07 16:47 UTC, merged